### ISSUE TITLE
求SDsoc安装包

### ISSUE THREAD

**Issue by RosabanksiaeAit** [WalkerLau/Accelerating-CNN-with-FPGA#2]
官网已经不提供下载了，想要复现您的实验，请问您的安装包还在吗？

**Comment by WalkerLau** [comment]
> 官网已经不提供下载了，想要复现您的实验，请问您的安装包还在吗？

不好意思，安装包太大了当时装完就删掉了。你可以通过这个官网链接下载：

https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vitis/archive-sdsoc.html

**Comment by RosabanksiaeAit** [comment]
啊，我在官网上找错地方了。感谢您的回复，祝您工作学习顺利！

**Comment by WalkerLau** [comment]
> 啊，我在官网上找错地方了。感谢您的回复，祝您工作学习顺利！

不客气
