### ISSUE TITLE
调用opencv失败

### ISSUE THREAD

**Issue by RosabanksiaeAit** [WalkerLau/Accelerating-CNN-with-FPGA#3]
您好，照着您的教程编译的时候，出现了很多这样的错误：
test_face_recognizer.cpp:(.text+0x300): undefined reference to `cv::imread(cv::String const&, int)'
test_face_recognizer.cpp:(.text+0x308): undefined reference to `cv::String::deallocate()'
test_face_recognizer.cpp:(.text+0x3d0): undefined reference to `cv::Mat::create(int, int const*, int)'
test_face_recognizer.cpp:(.text+0x48c): undefined reference to `cv::fastFree(void*)'
test_face_recognizer.cpp:(.text+0x4f8): undefined reference to `cv::fastFree(void*)'
make: *** [Accelerating-CNN-with-FPGA.elf] Error 1
test_face_recognizer.cpp:(.text+0x508): undefined reference to `cv::String::allocate(unsigned long)'
test_face_recognizer.cpp:(.text+0x6e8): undefined reference to `cv::Mat::deallocate()'
test_face_recognizer.cpp:(.text+0x6f4): undefined reference to `cv::Mat::deallocate()'
test_face_recognizer.cpp:(.text+0x940): undefined reference to `cv::String::deallocate()'
但使用的reVISION版本跟您在教程中的看着是一样的，请问这种情况下应该怎么办？或者应该往那个方向去查资料呢？

**Comment by WalkerLau** [comment]
> 您好，照着您的教程编译的时候，出现了很多这样的错误：
> test_face_recognizer.cpp:(.text+0x300): undefined reference to `cv::imread(cv::String const&, int)' test_face_recognizer.cpp:(.text+0x308): undefined reference to `cv::String::deallocate()'
> test_face_recognizer.cpp:(.text+0x3d0): undefined reference to `cv::Mat::create(int, int const*, int)' test_face_recognizer.cpp:(.text+0x48c): undefined reference to `cv::fastFree(void*)'
> test_face_recognizer.cpp:(.text+0x4f8): undefined reference to `cv::fastFree(void*)' make: *** [Accelerating-CNN-with-FPGA.elf] Error 1 test_face_recognizer.cpp:(.text+0x508): undefined reference to `cv::String::allocate(unsigned long)'
> test_face_recognizer.cpp:(.text+0x6e8): undefined reference to `cv::Mat::deallocate()' test_face_recognizer.cpp:(.text+0x6f4): undefined reference to `cv::Mat::deallocate()'
> test_face_recognizer.cpp:(.text+0x940): undefined reference to `cv::String::deallocate()'
> 但使用的reVISION版本跟您在教程中的看着是一样的，请问这种情况下应该怎么办？或者应该往那个方向去查资料呢？

应该是没有成功调用到reVISION的OpenCV库，你再看看eetop里的教程，确认是不是每一步都完成了

**Comment by RosabanksiaeAit** [comment]
我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。

**Comment by WalkerLau** [comment]
> 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。

不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。

**Comment by WalkerLau** [comment]
> 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。

实在不行的话我今晚再帮你把原工程搞出来

**Comment by RosabanksiaeAit** [comment]
我安装的是2018.2的sdx，证书只加载了vivado的证书（因为看网上sdx安装教程的证书就用了vivadolicience）。打开sdx是正常可以打开的。之前第一次打开的时候似乎提示了需要别的产品的证书，但因为目前的使用都正常，我就忽略了。想跟您确认一下，您当时安装sdx时用的是哪个产品的证书呢？



---原始邮件---
发件人: "WalkerLau"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 中午12:05
收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<Accelerating-CNN-with-FPGA@noreply.github.com&gt;;
抄送: "RosabanksiaeAit"<1370392334@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3)




  
我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。
  
不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。

**Comment by WalkerLau** [comment]
> 我安装的是2018.2的sdx，证书只加载了vivado的证书（因为看网上sdx安装教程的证书就用了vivadolicience）。打开sdx是正常可以打开的。之前第一次打开的时候似乎提示了需要别的产品的证书，但因为目前的使用都正常，我就忽略了。想跟您确认一下，您当时安装sdx时用的是哪个产品的证书呢？
> […](#)
> ---原始邮件--- 发件人: "WalkerLau"<notifications@github.com&gt; 发送时间: 2020年7月28日(周二) 中午12:05 收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<Accelerating-CNN-with-FPGA@noreply.github.com&gt;; 抄送: "RosabanksiaeAit"<1370392334@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3) 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。 不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我当时用的是在xilinx官网申请的license，是免费的，有挺多项目选项的，我当时全选了，然后生成了一个license文件。之前我的license过期了也会报错，更新了license就好，你可以找找

**Comment by RosabanksiaeAit** [comment]
还有这种情况呀！非常感谢您的回复，谢谢!!



---原始邮件---
发件人: "WalkerLau"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 中午12:23
收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<Accelerating-CNN-with-FPGA@noreply.github.com&gt;;
抄送: "RosabanksiaeAit"<1370392334@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3)




  
我安装的是2018.2的sdx，证书只加载了vivado的证书（因为看网上sdx安装教程的证书就用了vivadolicience）。打开sdx是正常可以打开的。之前第一次打开的时候似乎提示了需要别的产品的证书，但因为目前的使用都正常，我就忽略了。想跟您确认一下，您当时安装sdx时用的是哪个产品的证书呢？
 …
 ---原始邮件--- 发件人: "WalkerLau"<notifications@github.com&gt; 发送时间: 2020年7月28日(周二) 中午12:05 收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<Accelerating-CNN-with-FPGA@noreply.github.com&gt;; 抄送: "RosabanksiaeAit"<1370392334@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3) 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。 不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我当时用的是在xilinx官网申请的license，是免费的，有挺多项目选项的，我当时全选了，然后生成了一个license文件。之前我的license过期了也会报错，更新了license就好，你可以找找

**Comment by RosabanksiaeAit** [comment]
> 
> 
> > 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。
> 
> 实在不行的话我今晚再帮你把原工程搞出来

我这边先试一下自己申请一下，但还不知道能不能拿出实验室的板子，如果您方便的话麻烦您了！

**Comment by RosabanksiaeAit** [comment]
> 
> 
> > 我安装的是2018.2的sdx，证书只加载了vivado的证书（因为看网上sdx安装教程的证书就用了vivadolicience）。打开sdx是正常可以打开的。之前第一次打开的时候似乎提示了需要别的产品的证书，但因为目前的使用都正常，我就忽略了。想跟您确认一下，您当时安装sdx时用的是哪个产品的证书呢？
> > […](#)
> > ---原始邮件--- 发件人: "WalkerLau"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月28日(周二) 中午12:05 收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<[Accelerating-CNN-with-FPGA@noreply.github.com](mailto:Accelerating-CNN-with-FPGA@noreply.github.com)>; 抄送: "RosabanksiaeAit"<[1370392334@qq.com](mailto:1370392334@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3) 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。 不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我当时用的是在xilinx官网申请的license，是免费的，有挺多项目选项的，我当时全选了，然后生成了一个license文件。之前我的license过期了也会报错，更新了license就好，你可以找找

我自己申请了证书，可是还是报一样的错了。

**Comment by WalkerLau** [comment]
> > > 我安装的是2018.2的sdx，证书只加载了vivado的证书（因为看网上sdx安装教程的证书就用了vivadolicience）。打开sdx是正常可以打开的。之前第一次打开的时候似乎提示了需要别的产品的证书，但因为目前的使用都正常，我就忽略了。想跟您确认一下，您当时安装sdx时用的是哪个产品的证书呢？
> > > […](#)
> > > ---原始邮件--- 发件人: "WalkerLau"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月28日(周二) 中午12:05 收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<[Accelerating-CNN-with-FPGA@noreply.github.com](mailto:Accelerating-CNN-with-FPGA@noreply.github.com)>; 抄送: "RosabanksiaeAit"<[1370392334@qq.com](mailto:1370392334@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3) 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。 不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 我当时用的是在xilinx官网申请的license，是免费的，有挺多项目选项的，我当时全选了，然后生成了一个license文件。之前我的license过期了也会报错，更新了license就好，你可以找找
> 
> 我自己申请了证书，可是还是报一样的错了。

好的，我今晚把工程发给你，你留个联系方式吧

**Comment by RosabanksiaeAit** [comment]
> 
> 
> > > > 我安装的是2018.2的sdx，证书只加载了vivado的证书（因为看网上sdx安装教程的证书就用了vivadolicience）。打开sdx是正常可以打开的。之前第一次打开的时候似乎提示了需要别的产品的证书，但因为目前的使用都正常，我就忽略了。想跟您确认一下，您当时安装sdx时用的是哪个产品的证书呢？
> > > > […](#)
> > > > ---原始邮件--- 发件人: "WalkerLau"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年7月28日(周二) 中午12:05 收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<[Accelerating-CNN-with-FPGA@noreply.github.com](mailto:Accelerating-CNN-with-FPGA@noreply.github.com)>; 抄送: "RosabanksiaeAit"<[1370392334@qq.com](mailto:1370392334@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3) 我从头重新尝试了一遍，还是同样的错误。而且在project explorer窗口中的include中能看到xfopencv。请问您的原工程还在吗？我的配置都是跟您一致的，或许我可以试试能否编译您的原始工程。 不好意思，我的工程在另一个电脑上，暂时取不出来。我没有遇到过这个问题，你的sdsoc是2018.2版本的吗？现在还可以尝试检查一下软件的license是否有足够的权限。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 我当时用的是在xilinx官网申请的license，是免费的，有挺多项目选项的，我当时全选了，然后生成了一个license文件。之前我的license过期了也会报错，更新了license就好，你可以找找
> > 
> > 
> > 我自己申请了证书，可是还是报一样的错了。
> 
> 好的，我今晚把工程发给你，你留个联系方式吧

1370392334@qq.com
麻烦您了！

**Comment by RosabanksiaeAit** [comment]
![无标题](https://user-images.githubusercontent.com/61778456/88639196-15d0fb80-d0ef-11ea-93d3-06361d627070.png)
![无标题2](https://user-images.githubusercontent.com/61778456/88639388-52045c00-d0ef-11ea-8789-707509fe87bf.png)
我跟另一个同学各自分开照您的教程走了一遍，但是出现同样的错误，应该不是操作不对的问题。

**Comment by RosabanksiaeAit** [comment]
打开test_face_recognizer.cpp，是可以看到报错说找不到的这几个函数。请问您知道这些函数的具体定义是在哪个文件中呢？是不是因为函数定义没有被include进去或者是链接器设置中没在library中设置进去呢？（这里我看了网上很多设置，还是有点懵，但结合您的教程知道要设置这两方面）。
![无标题3](https://user-images.githubusercontent.com/61778456/88646457-b9260e80-d0f7-11ea-8652-8d099c76580f.png)

**Comment by WalkerLau** [comment]
> 打开test_face_recognizer.cpp，是可以看到报错说找不到的这几个函数。请问您知道这些函数的具体定义是在哪个文件中呢？是不是因为函数定义没有被include进去或者是链接器设置中没在library中设置进去呢？（这里我看了网上很多设置，还是有点懵，但结合您的教程知道要设置这两方面）。
> ![无标题3](https://user-images.githubusercontent.com/61778456/88646457-b9260e80-d0f7-11ea-8652-8d099c76580f.png)

大概了解了，我今晚再联系你吧

**Comment by RosabanksiaeAit** [comment]
好的，先不打扰您了



---原始邮件---
发件人: "WalkerLau"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 下午5:42
收件人: "WalkerLau/Accelerating-CNN-with-FPGA"<Accelerating-CNN-with-FPGA@noreply.github.com&gt;;
抄送: "RosabanksiaeAit"<1370392334@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [WalkerLau/Accelerating-CNN-with-FPGA] 调用opencv失败 (#3)




  
打开test_face_recognizer.cpp，是可以看到报错说找不到的这几个函数。请问您知道这些函数的具体定义是在哪个文件中呢？是不是因为函数定义没有被include进去或者是链接器设置中没在library中设置进去呢？（这里我看了网上很多设置，还是有点懵，但结合您的教程知道要设置这两方面）。
 
  
大概了解了，我今晚再联系你吧

**Comment by RosabanksiaeAit** [comment]
调用opencv失败是因为没有设置这里：
![图片](https://user-images.githubusercontent.com/61778456/88771277-96583080-d1b1-11ea-88fc-1f2e54ea164f.png)
